export const strings = {
  appTitle: "Zoom Webinar Report",
  appTitleBrand: "Zoom",
  appTitleRest: "Webinar Report",
  appSubtitle: "Free in-browser tool for deduplicated attendee reports — your data never leaves your browser.",
  steps: { upload: "Upload", grouping: "Group by day", options: "Options", done: "Download" },
  upload: {
    prompt: "Drag & drop Zoom attendee CSVs here",
    browse: "or click to browse",
    inspecting: "Reading files…",
    invalidFile: "Not a recognized Zoom attendee report.",
    next: "Continue",
    noDate: "no date",
    attendees: "attendees",
  },
  grouping: {
    title: "Review the day grouping",
    hint: "Files were grouped by their report date. Drag any file to a different day.",
    unassigned: "Unassigned (no date detected) — place these into a day",
    addDay: "Add day",
    day: "Day",
    back: "Back",
    next: "Continue",
    resolveUnassigned: "Place or remove the unassigned files to continue.",
  },
  options: {
    title: "Report options",
    eventTitle: "Event title",
    eventTitlePlaceholder: "e.g. Spring Webinar 2026",
    thresholds: "Viewing-time thresholds (minutes)",
    thresholdsHint: "Adds a 'users by country' sheet filtered to people who watched at least N minutes.",
    addThreshold: "Add",
    minuteUnit: "min",
    back: "Back",
    generate: "Generate report",
  },
  generate: {
    working: "Building your report…",
    success: "Your report is ready.",
    download: "Download XLSX",
    startOver: "Start over",
    error: "Something went wrong building the report.",
    retry: "Try again",
  },
  results: {
    title: "Your report is ready",
    download: "Download XLSX",
    share: "Share link",
    shareCopied: "Link copied to clipboard",
    shareHint: "Shareable URL — contains only aggregated stats, no attendee data.",
    startOver: "Start over",
    createOwn: "Create your own report →",
    topLine: {
      unique: "Unique attendees",
      countries: "Countries",
      avg: "Avg watch",
      median: "Median",
      max: "Max",
    },
    panels: {
      topCountries: "Top countries",
      moreCountries: "Show all (+%n more)",
      showLess: "Show less",
      perDay: "Per-day attendance",
      thresholds: "Engagement thresholds",
      histogram: "Engagement time distribution",
      retention: "Retention curve",
      peak: "Peak concurrent viewers",
      peakAt: "at %time",
      rooms: "Room statistics",
    },
  },
} as const;
